"""initial_schema

Revision ID: 8d43f5f5d349
Revises: 
Create Date: 2025-11-26 15:56:32.948652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d43f5f5d349'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado',
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('estado_id')
    )
    op.create_index(op.f('ix_estado_estado_id'), 'estado', ['estado_id'], unique=False)
    op.create_table('empleados',
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('cedula', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('celular', sa.String(length=50), nullable=True),
    sa.Column('domicilio', sa.String(length=255), nullable=True),
    sa.Column('nacionalidad', sa.String(length=100), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.estado_id'], ),
    sa.PrimaryKeyConstraint('empleado_id'),
    sa.UniqueConstraint('cedula')
    )
    op.create_index(op.f('ix_empleados_empleado_id'), 'empleados', ['empleado_id'], unique=False)
    op.create_table('menu',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.estado_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['menu.menu_id'], ),
    sa.PrimaryKeyConstraint('menu_id')
    )
    op.create_index(op.f('ix_menu_menu_id'), 'menu', ['menu_id'], unique=False)
    op.create_table('perfil',
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.estado_id'], ),
    sa.PrimaryKeyConstraint('perfil_id')
    )
    op.create_index(op.f('ix_perfil_perfil_id'), 'perfil', ['perfil_id'], unique=False)
    op.create_table('perfil_menu',
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.menu_id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.perfil_id'], ),
    sa.PrimaryKeyConstraint('perfil_id', 'menu_id')
    )
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=255), nullable=False),
    sa.Column('contrasenia', sa.String(length=255), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.empleado_id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.estado_id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.perfil_id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_index(op.f('ix_usuarios_usuario'), 'usuarios', ['usuario'], unique=True)
    op.create_index(op.f('ix_usuarios_usuario_id'), 'usuarios', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_usuario_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('perfil_menu')
    op.drop_index(op.f('ix_perfil_perfil_id'), table_name='perfil')
    op.drop_table('perfil')
    op.drop_index(op.f('ix_menu_menu_id'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_empleados_empleado_id'), table_name='empleados')
    op.drop_table('empleados')
    op.drop_index(op.f('ix_estado_estado_id'), table_name='estado')
    op.drop_table('estado')
    # ### end Alembic commands ###
